INSERT INTO users (first_name, last_name, email) VALUES('Fabio', 'Di Giacomo Pepe', 'fabio@gmail.com');
INSERT INTO users (first_name, last_name, email) VALUES('Mario', 'Rossi', 'mario@gmail.com');
INSERT INTO users (first_name, last_name, email) VALUES('Luca', 'Bianchi', 'luca@gmail.com');

INSERT INTO books (title, author, isbn, created_at, deleted_at, number_of_complete_readings, plot) VALUES("Il profumo dell'asfalto", "Giancarlo Fisichella", "9788820066178", "2024-01-18 11:15:00", "", 0, "Hockenheimring, GP di Germania 1997. Per la prima volta mi trovo in testa. Difendo con tutta la tenacia che ho la mia posizione, ma al 39º giro mi esplode una gomma e la vittoria, che sentivo già mia, sfuma. A fine gara, Schumacher accosta la sua Ferrari e mi fa cenno di salire per portarmi in parata e dirmi, a modo suo, che sì, meritavo di vincere. Ecco, la Formula 1 per me è questo: oltre il gesto tecnico, c'è quel saliscendi di emozioni che ti proietta in cima al mondo a 300 chilometri all'ora per poi ributtarti a terra, c'è la disperazione di Mansell che spinge la sua monoposto e sviene a pochi metri dal traguardo, c'è la lite ai box per uno sgarro in pista e l'amicizia quando meno te l'aspetti. È alla mia idea di competizione, epica e umana insieme, che ho voluto dedicare questo libro: non è la strategia a fare la corsa perfetta, ma il sorpasso che toglie il fiato (favoloso Häkkinen a Spa nel 2000), l'impresa impossibile, le rivalità più accese, che sono poi quelle tra compagni di scuderia, come sanno bene Alonso e Hamilton. Ho ripensato ai grandi piloti che hanno segnato un'epoca, come Senna e Michael, tanto geniali in pista quanto sfaccettati fuori, ai retroscena del Circus, soprattutto durante la regia visionaria di Ecclestone, e agli ingegneri che tutto sanno calcolare meno la passione di noi che scendiamo in pista. Perché si dice che il profumo dell'asfalto, una volta che l'hai sentito, sia come una droga: non puoi più farne a meno e torna la scarica di adrenalina ogni volta che si spegne l'ultimo semaforo.");
INSERT INTO books (title, author, isbn, created_at, deleted_at, number_of_complete_readings, plot) VALUES("Harry Potter e la pietra filosofale", "J. K. Rowling", "9788831003384", "2024-01-10 11:20:00", "", 2, "«Girando la busta con mano tremante, Harry vide un sigillo di ceralacca color porpora con uno stemma araldico: un leone, un'aquila, un tasso e un serpente intorno a una grossa H». Tutto comincia da qui. Il primo capitolo di uno dei più grandi fenomeni letterari internazionali, il libro che ha fatto leggere milioni di ragazzi e ha unito genitori e figli nella scoperta di un universo fantastico che è già parte dell'immaginario collettivo. Edizione speciale con contenuti inediti: la mappa di Hogwarts, il glossario, curiosità sui fondatori di Hogwarts.");
INSERT INTO books (title, author, isbn, created_at, deleted_at, number_of_complete_readings, plot) VALUES("La Divina Commedia: Inferno, Purgatorio e Paradiso", "Fabio Rivelli", "9798416411862", "2023-10-15 09:30:00", "2024-01-05 18:45:00", 1, "A 700 anni dalla morte di Dante, il poeta che ci ha regalato la massima opera letteraria mondiale, abbiamo realizzato una meravigliosa edizione integrale in unico volume che raccoglie Inferno, Purgatorio e Paradiso, volutamente impaginato senza annotamenti, (ma con gli utilissimi riassunti delle tre cantiche a fine libro) per restituire al lettore tutta l'emozione del capolavoro originale. Un'opera monumentale che ci viene invidiata in tutto il mondo e che il sommo poeta fiorentino Dante Alighieri ha saputo elevare a punto di riferimento globale per la letteratura non soltanto italiana, a partire dal '300. Un libro importante, in un formato da biblioteca personale, ad un prezzo conveniente, che non può mancare nella tua collezione.");

INSERT INTO users_books (user_id, books_id) VALUES(1, 1);
INSERT INTO users_books (user_id, books_id) VALUES(1, 2);
INSERT INTO users_books (user_id, books_id) VALUES(1, 3);
INSERT INTO users_books (user_id, books_id) VALUES(2, 2);
INSERT INTO users_books (user_id, books_id) VALUES(2, 3);
INSERT INTO users_books (user_id, books_id) VALUES(3, 1);